export const ACCESS_TOKEN_EXPIRES_IN = 'ACCESS_TOKEN_EXPIRES_IN';
export const ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET';
export const REFRESH_TOKEN_EXPIRES_IN = 'REFRESH_TOKEN_EXPIRES_IN';
export const REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET';
